# Generated by Django 4.1.1 on 2022-09-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="urlShortener",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("longurl", models.CharField(max_length=220)),
                ("shorturl", models.CharField(max_length=15)),
            ],
        ),
    ]
